### ISSUE TITLE
parse_string requires two characters after '\'

### ISSUE THREAD

**Issue by phillid** [mkfifo/dodo#18]
When `parse_string`'s escape character `\` was implemented, it was told to manually increment the index. This action is also perfomed each iteration in the `for` loop, so should be removed, and `len`'s increment adjusted accordingly

**Comment by phillid** [comment]
I have fixed this in my local copy, and will push it to my fork over the next few days as I address other issues I introduced with my repl

**Comment by chrisosaurus** [comment]
@phillid closing this issue as it was fixed in #19, please correct me if I am wrong.
