### ISSUE TITLE
improve documentation to mention escape character

### ISSUE THREAD

**Issue by chrisosaurus** [mkfifo/dodo#4]
the documentation is currently lacking any mention of the escape character '\' which is useful within a string for including '/' characters

example:
`e/hello\/world/` which will expect the string `hello/world`

**Comment by chrisosaurus** [comment]
This could be as simple as updating the example in the README to match the example from `make test` and maybe having a small section quickly mentioning '\'.

**Comment by chrisosaurus** [comment]
@phillid is that commit ready for merging in? I didn't see a PR so I haven't merged it in yet.

**Comment by phillid** [comment]
@mkfifo, I was going to add a man page first. That's all done and a PR is created.

**Comment by chrisosaurus** [comment]
c-c-c-c-combo! thanks @phillid
